glokascom/bibleVis

.github/ISSUE_TEMPLATE/BUG.yaml, .github/ISSUE_TEMPLATE/FEATURE.yaml, .github/ISSUE_TEMPLATE/TESTING.yaml
Added form template for issues
=> feat: :sparkles: add templates of issues

.prettierrc, package.json, yarn.lock
=> auto ordering of imports

.eslintignore, .github/workflows/ci.yml, .husky/commit-msg, .husky/pre-commit, commitlint.config.mjs, package.json, yarn.lock
=> Feat lint commits denisarger 4

app/[lng]/about/page.js, app/[lng]/page.jsx, app/api/hello/route.js, app/doc/layout.js, app/doc/page.js, app/doc/swagger.js, middleware.js, next-swagger-doc.json, next.config.mjs, package.json, public/swagger.json, yarn.lock
Add test api and swagger documentation
=> Feat swagger denisarger 10

app/(web)/page.tsx, app/components/CustomToast.tsx, app/components/NotificationButtons.tsx, app/components/ToastProvider.tsx, app/layout.tsx, app/providers.tsx, package.json, yarn.lock
=> Feature uitoast denisarger 67

app/(web)/user/edit/actions/updateUsername.js, app/(web)/user/edit/components/UsernameEdit.jsx
добавлено использование тостов на странице /user/edit
позиция тостов исправлена в ПР https://github.com/glokascom/bibleVis/pull/131
=> [Bug]: When change the same username - can't see error #126

app/(web)/image/download/page.js, app/api/auth/google/callback/route.ts, app/api/download-image/route.js, app/api/upload-image/route.ts, app/components/Download.jsx, app/components/ImagePageContent.jsx
=> Feature denisarger 110

app/(web)/user/edit/components/ImageUpload.jsx, app/components/ImageFormDisplay.jsx, app/components/TagInput.jsx, supabase/migrations/20240913121911_update_software.sql, supabase/seed.sql
#127 #104 #117 
- добавлен лоадинг при загрузке аватара
- добавлен фильтр для software
- добавлено заполнение тегов чрез запятую
=> Feature denisarger 104

app/(web)/[@username]/actions/imagesActions.ts, app/(web)/[@username]/components/Gallery.js, app/(web)/[@username]/page.js, app/components/ImageForGallery.jsx, app/components/ImagePageContent.jsx, app/components/LikesCounter.jsx, app/components/Modal.tsx, app/components/RelatedImages.jsx, public/polygon.svg
- обновлено отображение блока "More by..." в мобильной версии
- в галерее клик по картинке открывает модальное окно с просмотром картинки и возможностью переключать картинки
- в модальном окне изменяется url в соответствии с картинкой. При обновлении страницы мы переходим на страницу просмотра картинки
- исправлена ошибка гидрации при загрузке галереи
- лайки работают некорректно в галерее и модалке
=> [Feature]: Modal view image #123

app/(web)/[@username]/components/UserInfo.tsx, app/(web)/user/edit/components/ImageUpload.jsx, app/components/BVButton.jsx, app/components/BVButton.tsx, app/components/DeleteConfirmationModal.jsx, app/components/SaveConfirmationModal.jsx, app/components/ToastProvider.tsx, public/spinner.svg
1) кнопки, у которых используется состояние isLoading теперь не меняют свой текст, они лишь дополнительно отображают 
соответствующую анимированную иконку
2) страница "/user/edit": для адаптивного дизайна решил изменять такст (чем меньше ширина блока, тем меньше сам текст кнопки)
3) компонент BVButton обновлён кастомным Spinner и переписан на ts
4) модальное окно с диалогом удаления теперь закрывается после успешной операции
5) тосты теперь отображаются поверх блока с отображением основной картинки в компоненте ImageFormDisplay
close #142
=> [Feature]:Make same loading #142

app/(web)/[@username]/actions/imagesActions.ts, app/(web)/[@username]/components/Gallery.jsx, app/(web)/s/[title]/page.js, app/components/BVDropdown.jsx, app/components/Chevron.jsx, app/components/Download.jsx, public/chevron.svg
- loadNextPage обрабатывает запрос на title
- Gallery обрабатывает запрос на title
- в Gallery добавил проп isShowHeader, чтобы скрывать заголовок компонента для страницы поиска
- страница поиска: добавлены фильтры, но не настроены; галерея отображает запрашиваемые картинки по заголовку
- добавлен компонент BVDropdown для корректного отображения опций фильтра
- svg chevron был изменён на компонент Chevron для корректных изменений цвета и размеров картинки
=> [Feature]:Search page UI #119

app/components/ImageForGallery.jsx
- при открытии модалки с подтверждением удаления картинки сейчас закрывается модалка с опциями картинки ("Image Actions")
- добавлено градиентное затемнение картинки
- если открыта модалка "Image Actions", градиентное затемнение теперь продолжает работать на картинке
=> [Bug]: В галерее не верно сверстана картинка #179

app/(full-width)/success-sign-up/page.js, app/(web)/[@username]/actions/imagesActions.ts, app/(web)/[@username]/actions/userActions.ts, app/(web)/image/[title]/page.js, app/components/CreatorDetails.jsx, app/components/ImageForGallery.jsx, app/components/ImagePageContent.jsx, app/components/SuccessSignUp.jsx, app/components/TagInput.jsx, supabase/migrations/20240925100911_update_trigger.sql
#180 - edit count view image
#198 - synchonize follow
#170 - show avatar on image in gallary
#185 - fixed  success sign-up component
=> Bug denisarger 180

.vscode/settings.json, app/(web)/page.tsx, app/components/CustomToast.tsx, app/components/NotificationButtons.tsx, app/components/TagInput.jsx, app/components/ToastProvider.tsx
#184 - edit position toats
#194 - edit style toasts
#183 - edit bag in tagInput
=> Bug denisarger 184

app/(web)/pages/layout.js, app/(web)/pages/license/page.js, public/check-mark-green.svg, public/close-red.svg
[#157 [UI]:License Page](https://github.com/glokascom/bibleVis/issues/157)
=> [UI]:License Page #157

app/(web)/user/upload/components/UploadImage.jsx, app/(web)/user/upload/page.js, app/components/ImageUploadDragDrop.jsx
- скорректировано отображение основного контента для разрешения HD
=> [UI]:Upload Page adaptive 1280

app/(web)/user/upload/components/UploadImage.jsx, app/components/ImageUploadDragDrop.jsx
=> [UI]:Change UI in upload page #235

app/(web)/user/upload/components/UploadImage.jsx, app/components/ImageFormDisplay.jsx, supabase/migrations/20241017132900_change_columns_in_images.sql
1. Change limit letters for prompt and description to 1000
2. Added software  Krea.ai and Other option.
3. Success page - avatar now is the link to account
=> Change limit letters for prompt and description

app/components/ImagePageContent.jsx
На странице поиска, если выбрать фильтры и просматривать в модальном окне картинки - фильтры не пропадают
=> fix: fixed url on search page

app/(web)/user/edit/helper/сropImage.js, app/components/ServerImage.jsx, tailwind.config.js
Correct vertical image in mobile
=> Feature 272 Vertical image in mobile
